### ISSUE TITLE
Gradle plugin not supported

### ISSUE THREAD

**Issue by 7kashif** [mobiledevpro/Android-Jetpack-Compose-MVI-Template#6]
I am trying to build this project on Android Studio Flamingo | 2022.2.1 Beta 2, but it is giving me following error while building, I have tried degrading the AGP version but it didn't workout. Please guid with a solution or the Android Studio version that you have used to.

<img width="1042" alt="Screenshot 2023-02-10 at 13 02 42" src="https://user-images.githubusercontent.com/59311205/218035874-c182d6a4-4b74-466f-ab57-827a1f59c906.png">

**Comment by dmitriy-chernysh** [comment]
@7kashif I'm using Android Studio Giraffe | 2022.3.1 Canary 3 .  It seems Flamingo doesn't support Gradle 8.1  yet
As a solution, you can downgrade a Gradle version on your side to launch the project in Flamingo. 

![image](https://user-images.githubusercontent.com/5750211/218091042-35dc3ef1-8ca8-45d1-af5a-fd2f473ce97c.png)

**Comment by 7kashif** [comment]
Thanks a lot. It worked.

**Comment by dmitriy-chernysh** [comment]
Welcome
